name: ci
on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  test:
    name: test
    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: 1
      CROSS_URL: https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-musl.tar.gz
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            rust: stable
            cargo: cargo
            target: x86_64-unknown-linux-gnu

          - build: x86_64-unknown-linux-musl
            os: ubuntu-latest
            rust: stable
            cargo: cross
            target: x86_64-unknown-linux-musl

          - build: x86_64-pc-windows-msvc
            os: windows-latest
            rust: stable
            cargo: cargo
            target: x86_64-pc-windows-msvc

          # Check the least version
          - build: by-rust-1.92
            os: ubuntu-latest
            rust: 1.92.0
            cargo: cargo
            target: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          add-job-id-key: "false"
          add-rust-environment-hash-key: "false"

      - name: Install cross
        if: matrix.cargo == 'cross'
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Print info
        run: ${{ matrix.cargo }} --version

      - name: Build luatalk
        run: ${{ matrix.cargo }} build --verbose --target ${{ matrix.target }}

      - name: Run tests
        run: ${{ matrix.cargo }} test

  fmt-and-clippy:
    name: Ensure code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt,clippy

      - run: cargo fmt --all --check

      - run: cargo clippy -- --deny warnings

  doc:
    name: Check documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check documentation
        run: cargo doc --no-deps --document-private-items
